"""Add User model

Revision ID: 825ddd3c7aad
Revises: b6cf6d473444
Create Date: 2025-05-04 18:02:58.608384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825ddd3c7aad'
down_revision = 'b6cf6d473444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
